### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by BaiBlowSnow** [AoiKagase/Amxx-PSD-Frontend#1]
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in G:\www\includes\page_main.inc on line 2

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.;C:\php\pear') in G:\www\includes\page_main.inc on line 2

**Comment by AoiKagase** [comment]
It uses twig, flag-icon-css, and geoip2 as libraries.
Please use Composer to update.
`composer update`.
